dis = float(input('distancia (em metros): '))
km = dis / 1000
hm = dis / 100
dam = dis / 10
dm = dis * 10
cm = dis * 100
mm = dis * 1000
print(km,'km',sep='')
print(hm,'hm',sep='')
print(dam,'dam',sep='')
print(dm,'dm',sep='')
print(cm,'cm',sep='')
print(mm,'mm',sep='')
